import type { LandingPageConfig } from "@lp-admin/shared";

const EN_DRAMAS = [
  { name: "Double Life of a Cell Block King", tag: "New", coverUrl: "/assets/drama-1.webp", gradientFrom: "#3a1c71", gradientTo: "#ff7a45" },
  { name: "Breaking My Bodyguard", tag: "Hot", coverUrl: "/assets/drama-2.webp", gradientFrom: "#0f766e", gradientTo: "#ffc83d" },
  { name: "The Hockey Captain That Hates Me", tag: "Top", coverUrl: "/assets/drama-3.webp", gradientFrom: "#1d4ed8", gradientTo: "#fb3763" },
];

const EN_STEPS = [
  { icon: "📥", title: "1. Click 'Download Anyway'", description: "Android displays a standard alert for apps downloaded outside Google Play. Our app is 100% safe and verified.", tip: 'Click <strong style="color: var(--gold);">"Download anyway"</strong> when prompted.' },
  { icon: "📂", title: "2. Open the APK File", description: 'Once the download is complete, tap the notification or go to your device\'s "Downloads" folder.' },
  { icon: "⚙️", title: "3. Enable Installation (If Prompted)", description: 'If your browser asks for permission to install apps, tap <strong>Settings</strong> and toggle on <strong>"Allow from this source"</strong>.' },
  { icon: "🎉", title: "4. Install & Claim ₹3,000!", description: 'Tap <strong>"Install"</strong>, sign up, and start watching to claim your cash reward instantly.' },
];

export const DEFAULT_EN_LANDING: Omit<LandingPageConfig, "id" | "customerId" | "productId" | "createdAt" | "updatedAt"> = {
  name: "Mini Short - India EN",
  locale: "en",
  status: "active",
  pageTitle: "Mini Short - Watch Free Short Dramas",
  metaDescription: "Mini Short is a free short drama app with fast episodes, trending stories, and new-user reward campaigns.",
  brandName: "Mini Short",
  brandSubtitle: "Short dramas on mobile",
  logoUrl: "/assets/logo.png",
  bannerUrl: "/assets/banner.avif",
  rewardText: "₹3,000 Reward",
  downloadUrl: "https://xhxk6xeo20ip.trendovixx.com/2QsqMNTRX",
  pixelId: "4377607675843081",
  leadStorageKey: "mini_short_lead_tracked_at",
  heroTag: "Free Short Dramas",
  heroTitle: "Watch Free & Claim a ₹3,000 Cash Reward",
  heroDescription: "Download Mini Short to enjoy free episodes. Eligible new users can claim a ₹3,000 reward after completing campaign steps.",
  heroCtaText: "Download & Claim Reward",
  securityBadgeText: "Verified by Google Play Protect | 100% Virus-Free",
  dramasSectionTitle: "Trending Dramas",
  dramasSectionSubtitle: "Unlock More",
  dramas: EN_DRAMAS,
  installGuideTitle: "APK Installation Guide",
  installGuideSubtitle: "100% Safe & Verified",
  installSteps: EN_STEPS,
  finalTitle: "Watch for Free Today",
  finalDescription: "Install Mini Short, enjoy trending episodes for free, and check your eligibility for the new-user cash reward.",
  finalCtaText: "Download Mini Short",
  footerText: "Mini Short episodes are free to watch. The ₹3,000 new-user reward is available to eligible users who complete the campaign requirements. Availability may vary by region, campaign rules, and account status.",
  modalTitlePrefix: "Watch ",
  modalDescription: 'To watch this episode in English, please download our official <strong>Mini Short</strong> app. New users can also claim their <strong>₹3,000 cash reward</strong> instantly!',
  modalCtaText: "Download & Play",
  modalCancelText: "Cancel",
};

export const DEFAULT_MX_LANDING: Omit<LandingPageConfig, "id" | "customerId" | "productId" | "createdAt" | "updatedAt"> = {
  name: "Mini Short - Mexico ES",
  locale: "es-MX",
  status: "active",
  pageTitle: "Mini Short - Mira novelas cortas gratis",
  metaDescription: "Mini Short es una app gratuita de novelas cortas con capítulos rápidos, historias en tendencia y campañas de premios para nuevos usuarios.",
  brandName: "Mini Short",
  brandSubtitle: "Novelas cortas en móvil",
  logoUrl: "/assets/logo.png",
  bannerUrl: "/assets/banner.avif",
  rewardText: "$688 MXN",
  downloadUrl: "https://gx3zfy6e608w.torvantisx.com/PBinfdspFI",
  pixelId: "4377607675843081",
  leadStorageKey: "mini_short_mx_lead_tracked_at",
  heroTag: "Novelas cortas gratis",
  heroTitle: "Mira gratis y reclama $688 MXN de premio",
  heroDescription: "Descarga Mini Short para disfrutar episodios gratis. Los nuevos usuarios elegibles pueden reclamar $688 MXN al completar los pasos de la campaña.",
  heroCtaText: "Descargar y reclamar premio",
  securityBadgeText: "Verificado por Google Play Protect | 100% libre de virus",
  dramasSectionTitle: "Novelas en tendencia",
  dramasSectionSubtitle: "Desbloquear más",
  dramas: EN_DRAMAS.map((d) => ({ ...d, name: d.name })),
  installGuideTitle: "Guía de instalación APK",
  installGuideSubtitle: "100% seguro y verificado",
  installSteps: [
    { icon: "📥", title: "1. Haz clic en 'Descargar de todos modos'", description: "Android muestra una alerta estándar para apps descargadas fuera de Google Play. Nuestra app es 100% segura.", tip: 'Haz clic en <strong style="color: var(--gold);">"Descargar de todos modos"</strong> cuando aparezca.' },
    { icon: "📂", title: "2. Abre el archivo APK", description: "Cuando termine la descarga, toca la notificación o ve a la carpeta Descargas." },
    { icon: "⚙️", title: "3. Habilita la instalación (si se solicita)", description: 'Si el navegador pide permiso, toca <strong>Configuración</strong> y activa <strong>"Permitir desde esta fuente"</strong>.' },
    { icon: "🎉", title: "4. ¡Instala y reclama $688 MXN!", description: 'Toca <strong>"Instalar"</strong>, regístrate y empieza a ver para reclamar tu premio.' },
  ],
  finalTitle: "Mira gratis hoy",
  finalDescription: "Instala Mini Short, disfruta episodios en tendencia gratis y verifica tu elegibilidad para el premio de nuevo usuario.",
  finalCtaText: "Descargar Mini Short",
  footerText: "Los episodios de Mini Short son gratis. El premio de $688 MXN está disponible para usuarios elegibles que completen los requisitos de la campaña.",
  modalTitlePrefix: "Ver ",
  modalDescription: 'Para ver este episodio en español, descarga nuestra app oficial <strong>Mini Short</strong>. ¡Los nuevos usuarios también pueden reclamar <strong>$688 MXN</strong> al instante!',
  modalCtaText: "Descargar y ver",
  modalCancelText: "Cancelar",
};

export const DEFAULT_CO_LANDING: Omit<LandingPageConfig, "id" | "customerId" | "productId" | "createdAt" | "updatedAt"> = {
  name: "Mini Short - Colombia ES",
  locale: "es-CO",
  status: "active",
  pageTitle: "Mini Short - Mira novelas cortas gratis",
  metaDescription: "Mini Short es una app gratuita de novelas cortas con capítulos rápidos, historias en tendencia y campañas de premios para nuevos usuarios.",
  brandName: "Mini Short",
  brandSubtitle: "Novelas cortas en el celular",
  logoUrl: "/assets/logo.png",
  bannerUrl: "/assets/banner.avif",
  rewardText: "$120.000 COP",
  downloadUrl: "https://gx3zfy6e608w.torvantisx.com/PBinfdspFI",
  pixelId: "4377607675843081",
  leadStorageKey: "mini_short_co_lead_tracked_at",
  heroTag: "Novelas cortas gratis",
  heroTitle: "Mira gratis y reclama $120.000 COP de premio",
  heroDescription: "Descarga Mini Short para disfrutar episodios gratis. Los nuevos usuarios elegibles pueden reclamar $120.000 COP al completar los pasos de la campaña.",
  heroCtaText: "Descargar y reclamar premio",
  securityBadgeText: "Verificado por Google Play Protect | 100% libre de virus",
  dramasSectionTitle: "Novelas en tendencia",
  dramasSectionSubtitle: "Desbloquear más",
  dramas: EN_DRAMAS.map((d) => ({ ...d, name: d.name })),
  installGuideTitle: "Guía de instalación APK",
  installGuideSubtitle: "100% seguro y verificado",
  installSteps: [
    { icon: "📥", title: "1. Haz clic en 'Descargar de todos modos'", description: "Android muestra una alerta estándar para apps descargadas fuera de Google Play. Nuestra app es 100% segura.", tip: 'Haz clic en <strong style="color: var(--gold);">"Descargar de todos modos"</strong> cuando aparezca.' },
    { icon: "📂", title: "2. Abre el archivo APK", description: "Cuando termine la descarga, toca la notificación o ve a la carpeta Descargas." },
    { icon: "⚙️", title: "3. Habilita la instalación (si se solicita)", description: 'Si el navegador pide permiso, toca <strong>Configuración</strong> y activa <strong>"Permitir desde esta fuente"</strong>.' },
    { icon: "🎉", title: "4. ¡Instala y reclama $120.000 COP!", description: 'Toca <strong>"Instalar"</strong>, regístrate y empieza a ver para reclamar tu premio.' },
  ],
  finalTitle: "Mira gratis hoy",
  finalDescription: "Instala Mini Short, disfruta episodios en tendencia gratis y verifica tu elegibilidad para el premio de nuevo usuario.",
  finalCtaText: "Descargar Mini Short",
  footerText: "Los episodios de Mini Short son gratis. El premio de $120.000 COP está disponible para usuarios elegibles que completen los requisitos de la campaña.",
  modalTitlePrefix: "Ver ",
  modalDescription: 'Para ver este episodio en español, descarga nuestra app oficial <strong>Mini Short</strong>. ¡Los nuevos usuarios también pueden reclamar <strong>$120.000 COP</strong> al instante!',
  modalCtaText: "Descargar y ver",
  modalCancelText: "Cancelar",
};
